# Generated by Django 4.2.24 on 2025-09-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_ownermodel_busmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='busimages'),
        ),
    ]
