# Generated by Django 4.2.24 on 2025-09-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_busmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
