# Generated by Django 4.2.24 on 2025-09-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_busroutesmodel_busstopmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='status',
            field=models.CharField(blank=True, default='Available', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AssignBusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('BusId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.busmodel')),
                ('RouteId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.busroutesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AssignBusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.busmodel')),
                ('DriverId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.drivermodel')),
            ],
        ),
    ]
