# Generated by Django 4.2.24 on 2025-09-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0006_drivermodel_status_assignbusroute_assignbusdriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermodel',
            name='status',
        ),
    ]
