# Generated by Django 4.2.24 on 2025-09-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0008_alter_assignbusroute_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Idproof', models.FileField(null=True, upload_to='Id_Proof/')),
                ('BusId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.busmodel')),
            ],
        ),
    ]
