# Generated by Django 4.2.24 on 2025-09-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0009_conductormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=100, null=True)),
                ('WorshopName', models.CharField(max_length=100, null=True)),
                ('Login_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.loginmodel')),
            ],
        ),
    ]
