# Generated by Django 4.2.24 on 2025-09-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0011_assignworkshopmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignworkshopmodel',
            name='Complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
