# Generated by Django 4.2.24 on 2025-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0012_assignworkshopmodel_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
