# Generated by Django 4.2.24 on 2025-10-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0014_locationtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.loginmodel')),
            ],
        ),
    ]
