# Generated by Django 4.2.24 on 2025-10-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0015_usertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='FullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.loginmodel'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
